#!/bin/bash
# scripts/generate_env.sh
#
# Run this AFTER every "terraform apply".
# Reads all endpoints and IDs from Terraform outputs and writes
# them to app/.env so nothing is ever hardcoded.
#
# Usage: bash scripts/generate_env.sh

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
TF_DIR="$REPO_ROOT/terraform"

echo "📋 Reading Terraform outputs..."
cd "$TF_DIR"

# ── Read all outputs ──────────────────────────────────────────────────────────
AWS_REGION=$(terraform output -raw aws_region)
PROJECT_NAME=$(terraform output -raw project_name)
BASTION_IP=$(terraform output -raw bastion_public_ip)
RDS_ENDPOINT=$(terraform output -raw rds_endpoint)
ALB_DNS=$(terraform output -raw alb_dns_name)
PRIVATE_SUBNET_ID=$(terraform output -raw private_subnet_id)
VPC_ID=$(terraform output -raw vpc_id)

# S3 buckets — constructed from project name + account ID
ACCOUNT_ID=$(terraform output -raw account_id)
S3_BUCKET_DOCS="${PROJECT_NAME}-docs-${ACCOUNT_ID}"
S3_BUCKET_REPORTS="${PROJECT_NAME}-reports-${ACCOUNT_ID}"

# DynamoDB tables
DYNAMODB_AUDIT_TABLE="${PROJECT_NAME}-audit-log"
DYNAMODB_INCIDENTS_TABLE="${PROJECT_NAME}-incidents"
DYNAMODB_MEETINGS_TABLE="${PROJECT_NAME}-meetings"

# Lambda function name
LAMBDA_BLOCK_IP_NAME="${PROJECT_NAME}-block-ip"

# SNS topic ARN
SNS_TOPIC_SECURITY_ARN="arn:aws:sns:${AWS_REGION}:${ACCOUNT_ID}:${PROJECT_NAME}-security-alert"
SNS_TOPIC_MEETING_REMINDERS="arn:aws:sns:${AWS_REGION}:${ACCOUNT_ID}:${PROJECT_NAME}-meeting-reminders"

echo "✅ Bastion IP:    $BASTION_IP"
echo "✅ RDS Endpoint:  $RDS_ENDPOINT"
echo "✅ ALB DNS:       $ALB_DNS"
echo "✅ Region:        $AWS_REGION"

# ── Read sensitive values from terraform.tfvars ────────────────────────────────
# These are not outputs (sensitive = true) so we read tfvars directly
TFVARS="$TF_DIR/terraform.tfvars"

read_tfvar() {
  grep "^$1" "$TFVARS" | sed 's/.*= *"//' | sed 's/".*//'
}

DB_PASSWORD=$(read_tfvar "db_password")
JWT_SECRET_KEY=$(read_tfvar "jwt_secret_key")
SLACK_WEBHOOK_URL=$(read_tfvar "slack_webhook_url")
TELEGRAM_BOT_TOKEN=$(read_tfvar "telegram_bot_token")
TELEGRAM_CHAT_ID=$(read_tfvar "telegram_chat_id")
DB_USERNAME=$(read_tfvar "db_username")

# DB URL — asyncpg format for FastAPI SQLAlchemy
DB_HOST="$RDS_ENDPOINT"
WRITE_DB_URL="postgresql+psycopg2://${DB_USERNAME}:${DB_PASSWORD}@${RDS_ENDPOINT}:5432/${PROJECT_NAME}"
READ_DB_URL="$WRITE_DB_URL"

# ── Write app/.env ─────────────────────────────────────────────────────────────
cat > "$REPO_ROOT/app/.env" << EOF
# Auto-generated by scripts/generate_env.sh — do not edit manually
# Run 'bash scripts/generate_env.sh' after every terraform apply

# ── AWS ──────────────────────────────────────────────────────
AWS_REGION=${AWS_REGION}
PROJECT_NAME=${PROJECT_NAME}

# ── Database ─────────────────────────────────────────────────
WRITE_DB_URL=${WRITE_DB_URL}
READ_DB_URL=${READ_DB_URL}
DB_HOST=${DB_HOST}
DB_PASSWORD=${DB_PASSWORD}

# ── S3 ───────────────────────────────────────────────────────
S3_BUCKET_DOCS=${S3_BUCKET_DOCS}
S3_BUCKET_REPORTS=${S3_BUCKET_REPORTS}

# ── DynamoDB ─────────────────────────────────────────────────
DYNAMODB_AUDIT_TABLE=${DYNAMODB_AUDIT_TABLE}
DYNAMODB_INCIDENTS_TABLE=${DYNAMODB_INCIDENTS_TABLE}
DYNAMODB_MEETINGS_TABLE=${DYNAMODB_MEETINGS_TABLE}

# ── Lambda ───────────────────────────────────────────────────
LAMBDA_BLOCK_IP_NAME=${LAMBDA_BLOCK_IP_NAME}

# ── SNS ──────────────────────────────────────────────────────
SNS_TOPIC_SECURITY_ARN=${SNS_TOPIC_SECURITY_ARN}
SNS_TOPIC_MEETING_REMINDERS=${SNS_TOPIC_MEETING_REMINDERS}

# ── Auth ─────────────────────────────────────────────────────
JWT_SECRET_KEY=${JWT_SECRET_KEY}

# ── Notifications ────────────────────────────────────────────
SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}

# ── Infrastructure ───────────────────────────────────────────
ALB_DNS=${ALB_DNS}
BASTION_IP=${BASTION_IP}
VPC_ID=${VPC_ID}
EOF

chmod 600 "$REPO_ROOT/app/.env"

echo ""
echo "✅ app/.env written successfully"
echo "   ALB health check: curl http://${ALB_DNS}/health"