#!/bin/bash
# ─────────────────────────────────────────────────────────────
# generate_env.sh
#
# Run this AFTER every "terraform apply".
# It reads IPs and endpoints from Terraform outputs and writes
# them to app/.env so nothing is ever hardcoded.
#
# Usage: bash scripts/generate_env.sh
# ─────────────────────────────────────────────────────────────

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
TF_DIR="$REPO_ROOT/terraform"

echo "📋 Reading Terraform outputs..."
cd "$TF_DIR"

BASTION_IP=$(terraform output -raw bastion_public_ip)
AWS_REGION=$(terraform output -raw aws_region)
PROJECT_NAME=$(terraform output -raw project_name)

echo "✅ Bastion IP: $BASTION_IP"
echo "✅ Region: $AWS_REGION"

# Write app/.env
cat > "$REPO_ROOT/app/.env" << EOF
# Auto-generated by scripts/generate_env.sh — do not edit manually
# Run 'bash scripts/generate_env.sh' after every terraform apply

AWS_REGION=${AWS_REGION}
PROJECT_NAME=${PROJECT_NAME}
BASTION_IP=${BASTION_IP}

# These will be added in Week 2 after RDS and ALB are created:
# DB_HOST=<from terraform output rds_endpoint>
# ALB_DNS=<from terraform output alb_dns_name>
# JWT_SECRET_KEY=<set manually>
# SLACK_WEBHOOK_URL=<set manually>
# TELEGRAM_BOT_TOKEN=<set manually>
# TELEGRAM_CHAT_ID=<set manually>
EOF

echo ""
echo "✅ app/.env has been written with current Terraform outputs."
echo "   Open app/.env and fill in the manually-set values."
